"""Render findings as HTML or JSON."""
from __future__ import annotations

import json
from datetime import datetime, timezone
from html import escape
from typing import Iterable, Sequence

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from config import SEVERITY_ORDER   # noqa: E402

from .detectors import Finding      # noqa: E402

SEVERITY_RANK = {s: i for i, s in enumerate(SEVERITY_ORDER)}
SEVERITY_COLOR = {
    "info":     "#5a6c7d",
    "low":      "#3a7d44",
    "medium":   "#c08300",
    "high":     "#b8470a",
    "critical": "#a31621",
}


def _grouped(findings: Sequence[Finding]) -> dict[str, list[Finding]]:
    out: dict[str, list[Finding]] = {s: [] for s in SEVERITY_ORDER}
    for f in findings:
        out.setdefault(f.severity, []).append(f)
    # Highest severity first when iterated.
    return {s: out[s] for s in reversed(SEVERITY_ORDER) if out[s]}


def _summary(findings: Sequence[Finding]) -> dict:
    counts = {s: 0 for s in SEVERITY_ORDER}
    by_detector: dict[str, dict[str, int]] = {}
    for f in findings:
        counts[f.severity] = counts.get(f.severity, 0) + 1
        by_detector.setdefault(f.detector, {s: 0 for s in SEVERITY_ORDER})
        by_detector[f.detector][f.severity] += 1
    return {
        "total":       len(findings),
        "by_severity": counts,
        "by_detector": by_detector,
    }


def to_json(findings: Iterable[Finding], pcap_path: str | None = None) -> str:
    flist = list(findings)
    doc = {
        "tool":         "meshtastic-security-audit",
        "version":      "0.1.0",
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "pcap":         pcap_path,
        "summary":      _summary(flist),
        "findings":     [f.to_dict() for f in flist],
    }
    return json.dumps(doc, indent=2, sort_keys=True)


# ─── HTML rendering ─────────────────────────────────────────────────
_HTML_HEAD = """\
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Meshtastic Security Audit — {pcap}</title>
<style>
 body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         margin: 1.5em; color: #111; background: #fafafa; }}
 h1   {{ margin-bottom: 0.1em; }}
 h1 small {{ font-weight: normal; color: #555; }}
 table {{ border-collapse: collapse; margin: 0.6em 0 1.4em; }}
 td, th {{ padding: 5px 9px; border: 1px solid #d8d8d8; }}
 th {{ background: #ececec; text-align: left; }}
 .sev {{ display: inline-block; padding: 2px 7px; border-radius: 3px;
         color: #fff; font-size: 0.85em; font-weight: bold; }}
 .finding {{ border-left: 4px solid #999; padding: 6px 12px; margin: 8px 0;
             background: #fff; }}
 .meta {{ font-family: ui-monospace, 'SF Mono', Consolas, monospace;
          font-size: 0.8em; color: #444;
          background: #f3f3f3; padding: 4px 6px; border-radius: 2px;
          display: inline-block; margin-top: 4px; }}
 footer {{ margin-top: 2em; color: #777; font-size: 0.85em; }}
</style>
</head>
<body>
"""

_HTML_TAIL = """\
<footer>
  Generated by meshtastic-security-audit v0.1.0 · {ts}
</footer>
</body>
</html>
"""


def _sev_badge(severity: str) -> str:
    color = SEVERITY_COLOR.get(severity, "#666")
    return f'<span class="sev" style="background:{color}">{severity.upper()}</span>'


def _meta(meta: dict) -> str:
    if not meta:
        return ""
    return '<div class="meta">' + escape(json.dumps(meta, sort_keys=True)) + "</div>"


def to_html(findings: Iterable[Finding], pcap_path: str | None = None) -> str:
    flist = list(findings)
    flist.sort(key=lambda f: (-SEVERITY_RANK.get(f.severity, 0), f.detector, f.frame_index or -1))
    summary = _summary(flist)
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    pcap_label = escape(str(pcap_path)) if pcap_path else "(no PCAP path recorded)"

    out: list[str] = [_HTML_HEAD.format(pcap=pcap_label)]
    out.append(f"<h1>Meshtastic security audit "
               f"<small>{pcap_label}</small></h1>")
    out.append(f"<p>Total findings: <strong>{summary['total']}</strong>.</p>")

    out.append("<h2>Severity breakdown</h2>")
    out.append("<table><tr>")
    for sev in SEVERITY_ORDER:
        c = summary["by_severity"].get(sev, 0)
        out.append(f"<th>{sev}</th>")
    out.append("</tr><tr>")
    for sev in SEVERITY_ORDER:
        c = summary["by_severity"].get(sev, 0)
        out.append(f"<td>{c}</td>")
    out.append("</tr></table>")

    out.append("<h2>By detector</h2>")
    out.append("<table><tr><th>Detector</th>")
    for sev in SEVERITY_ORDER:
        out.append(f"<th>{sev}</th>")
    out.append("</tr>")
    for det, counts in sorted(summary["by_detector"].items()):
        out.append(f"<tr><td>{escape(det)}</td>")
        for sev in SEVERITY_ORDER:
            out.append(f"<td>{counts.get(sev, 0)}</td>")
        out.append("</tr>")
    out.append("</table>")

    out.append("<h2>Findings (highest severity first)</h2>")
    for sev, flist_grp in _grouped(flist).items():
        out.append(f"<h3>{_sev_badge(sev)} &nbsp;{len(flist_grp)} finding(s)</h3>")
        for f in flist_grp:
            out.append('<div class="finding" style="border-left-color:'
                       f'{SEVERITY_COLOR.get(sev, "#999")}">')
            out.append(f"<strong>[{escape(f.detector)}]</strong> "
                       f"{escape(f.title)}")
            if f.frame_index is not None:
                out.append(f' <small>(frame #{f.frame_index})</small>')
            out.append(f"<br><span>{escape(f.description)}</span>")
            out.append(_meta(f.metadata))
            out.append("</div>")

    out.append(_HTML_TAIL.format(ts=ts))
    return "".join(out)
